@startuml

skinparam componentStyle uml2

package "User Interface" {}
package "Service Layer" {}
package "Persistence" {}

"User Interface" ..> "Service Layer"
"Service Layer" ..> "Persistence"

@enduml