@startuml


RequestHandler - [Analysis Dashboard]
[Analysis Dashboard] -..> [Spring Context]
[Analysis Dashboard] ..> [Spring Beans]
[Analysis Dashboard] ..> [Spring Web]
[Analysis Dashboard] ..> [Apache Commons]

[Analysis Dashboard] .> [Issues Service]
[Issues Service] -..> [Spring Context]
[Issues Service] ..> [Analysis Model]

[Issues Service] .> [Database Gateway]
[Database Gateway]..> [HikariCP]
[Database Gateway] -..> [Spring Context]

@enduml