@startuml

package "User Interface" {
}

package "Usecase Controller" {
}

package "Database Access" {
}

package "Utilities" {
}

"User Interface" .> "Usecase Controller"
"Usecase Controller" .> "Database Access"
"User Interface" ..> "Utilities"
"Usecase Controller" ..> "Utilities"
"Database Access" ..> "Utilities"

@enduml