@startuml

hide footbox

actor Actor
activate Actor
boundary LoginDialog
control AuthenticationController
control UserEntityService
entity User
boundary LdapService
boundary MainDialog

Actor -> LoginDialog : Username, Password
activate LoginDialog

LoginDialog -> AuthenticationController: login(username, password)
activate AuthenticationController

alt Benutzer Gefunden

AuthenticationController -> UserEntityService: findById(username)
activate UserEntityService

create User
UserEntityService -> User : map()
activate User

UserEntityService <-- User
deactivate User

AuthenticationController <-- UserEntityService : User
deactivate UserEntityService

AuthenticationController -> LdapService : authenticate(username, password)
activate LdapService
AuthenticationController <-- LdapService : AuthenticationToken
deactivate LdapService

create Session
AuthenticationController -> Session : new(username)

create MainDialog
AuthenticationController -> MainDialog : new()

else Benutzer nicht gefunden

activate UserEntityService
AuthenticationController <-- UserEntityService : Exception
deactivate UserEntityService
LoginDialog <- AuthenticationController : show

else Passwort falsch

activate LdapService

AuthenticationController <-- LdapService : AuthenticationFailure
deactivate LdapService
LoginDialog <- AuthenticationController : show

end



@enduml