@startuml

hide footbox

actor Actor
activate Actor

boundary Dashboard
boundary Upload
boundary Details

control DashboardController
control UploadController
control IssuesService
control IssuesEntityService
control EntityService
control IssueRepository
entity Issue
control IssuesRepository
entity Issues

Actor -> Dashboard: /upload
activate Dashboard

Dashboard -> DashboardController : createUpload(model)
activate DashboardController
destroy Dashboard

create Upload
DashboardController -> Upload: new / redirect
activate Upload
deactivate DashboardController

Actor <-- Upload

Actor -> Upload: select file
Actor -> Upload: choose tool
Actor -> Upload: set reference
Actor -> Upload: upload

Upload -> UploadController: upload(file, tool, reference)
activate UploadController

UploadController -> IssuesService: parse(file)
activate IssuesService
IssuesService -> IssuesService : findAllTools
IssuesService -> Parser : parse
activate Parser
IssuesService <-- Parser : Issues
deactivate Parser

IssuesService -> IssuesEntityService : save(issues)
activate IssuesEntityService

loop

    IssuesEntityService -> EntityService : select(id)
    activate EntityService
    
    EntityService -> IssueRepository : findById(id)
    activate IssueRepository
    
    create Issue
    IssueRepository -> Issue : new
    EntityService <-- IssueRepository : Issue
    deactivate IssueRepository
    
    IssuesEntityService <-- EntityService : Issue
    deactivate EntityService

end

IssuesEntityService -> EntityService : insert

activate EntityService


loop
EntityService -> IssueRepository : insert(issue)
activate IssueRepository
    
    create Issue
    IssueRepository -> Issue : new
    EntityService <-- IssueRepository : Issue
    deactivate IssueRepository
    
end

EntityService -> IssuesRepository : insert(issues)
activate IssuesRepository

create Issues
IssuesRepository -> Issues : new
EntityService <-- IssuesRepository : Issues
deactivate IssuesRepository

IssuesEntityService <-- EntityService : Issues
deactivate EntityService
IssuesService <-- IssuesEntityService : Issues
deactivate IssuesEntityService

UploadController <-- IssuesService: Issues
deactivate IssuesService

destroy Upload

create Details
UploadController -> Details: new / redirect
activate Details

deactivate UploadController


@enduml